config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :vendors
  devise_for :users

  # resources :users, only: [:show]
  # resources :carts, only: [:show, :destroy]

  resources :products
  resources :vendors do
    resources :products, only: [:index, :new, :create]
  end

  resources :orders do
    collection do
      get 'user_orders'
      get 'placed_orders'
    end
  end

  root "products#index"
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at","products"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["products"]
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :index]

  before_action :authenticate_vendor!, only: [:show, :index]

  def index
    @vendor_products = current_vendor.products
  end

  def new
    @product = current_vendor.products.build
  end

  def create
    @vendor_products = @vendor.products.build(vendor_params)
    if @vendor_products.save
      redirect_to vendor_path(@vendor), notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # def show
  #   byebug
  #   @product = @vendor.products.find(params[:id])
  #   # @order = current_user.orders.build
  #   # @vendor_products = @vendor.products.includes(:vendor_product)
  # end

  def show
    if current_vendor.present?
      @vendor_product = current_vendor.products || vendors
      byebug
      if @vendor_product.nil?
        redirect_to root_path, alert: 'vendor not found or not placed.'
      end
    else
      @products = Product.all
    end
  end

  private

  def set_vendor
    @vendor = current_vendor
  end

  def vendor_params
    params.require(:product).permit(:title, :description, :price)
  end

  def vendors
   if current_vendor.placed_orders
    @product = current_vendor.products.where(id: params[:id])
   end
  end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/index.html.erb
<!-- app/views/vendors/index.html.erb -->

<h1><%= @vendor.email %>'s Store</h1>

<% if @vendor_products.any? %>
  <ul>
    <% @vendor_products.each do |product| %>
      <li>
        <%= product.title %> - <%= product.price %> - <%= image_tag product.image, class: 'product-image' %>
        <%= link_to "View", vendor_path(@vendor) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No products available for this vendor.</p>
<% end %>

<%= link_to 'Back to Products', products_path %>
<%= button_to('Log Out', destroy_vendor_session_path, method: :delete) %>

app/views/vendors/new.html.erb
<!-- app/views/vendors/new.html.erb -->
<h1>Create a New Product</h1>

<%= form_for [@vendor, @product] do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div>
    <%= f.submit 'Create Product' %>
  </div>
<% end %>

<%= link_to 'Back to Products', vendors_path %>
<%= button_to(
        'Log Out',
        destroy_user_session_path,
        method: :delete
      ) %>

app/views/vendors/show.html.erb
<% if current_vendor.present? %>
  <h1><%= current_vendor.email %>'s Store</h1>

  <% if @vendor_products.present? %>
  <%byebug%>
  <ul>
      <li>
        <%= product.title %> - <%= product.price %> - <%= image_tag product.image, class: 'product-image' %>
        <%= link_to "View", vendor_path(@vendor) %>
      </li>
  </ul>
<% else %>
  <p>No products available for this vendor.</p>
<% end %>

  <%= link_to 'Back to Products', products_path %>
  <%= button_to 'Log Out', destroy_user_session_path, method: :delete %>
  <%= link_to "Add Product", new_vendor_product_path %>
<% else %>
  <%= link_to 'Back to Home', root_path %>
<% end %>