config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :vendors
  devise_for :users

  # resources :users, only: [:show]
  # resources :carts, only: [:show, :destroy]

  resources :products
  resources :vendors do
    resources :products, only: [:index, :new, :create]
  end

  resources :orders do
    collection do
      get 'user_orders'
      get 'placed_orders'
    end
  end

  root "products#index"
end

app/models/product.rb
class Product < ApplicationRecord
 belongs_to :vendor
 has_one_attached :image
 validates :image, presence: true
 has_many :orders, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "price", "title", "updated_at", "vendor_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["orders", "vendor", "image_attachment_id_eq"]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_vendor!

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    # @order = current_user.orders.build
  end

  def new
    @product = current_vendor.products.create
  end

  def create
    @product = current_vendor.products.build(product_params)
    @product.image.attach(params[:product][:image])

    if @product.save
      redirect_to vendors_path, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @product = current_vendor.products.find(params[:id])
    if @product.destroy
      redirect_to vendors_path, notice: 'Product was successfully deleted.'
    else
      redirect_to vendors_path, alert: 'Unable to delete the product.'
    end
end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :image)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<% if user_signed_in? %>
  <% if @products.present? %>
    <% @products.each do |product| %>
      <h3>
        <%= product.title %> -
        <%= product.description %> -
        <%= product.price %> -
        <% if product.image.attached? %>
          <%= image_tag product.image, class: 'product-image' %>
        <% else %>
          No image attached.
        <% end %>
        <%= link_to 'View', product %>
      </h3>
    <% end %>
  <% else %>
    <h2>No products available for this user.</h2>
  <% end %>
<% end %>


  <%= link_to "vendors product", orders_path %><br>
  <%= link_to "New Product added", new_vendor_path %>

<%= button_to(
    "Log Out",
    destroy_vendor_session_path,
    method: :delete
  ) %>

<% if user_signed_in? %>
  <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
<%end%>

app/views/products/new.html.erb
<!-- app/views/products/new.html.erb -->
<h1>New Product</h1>

<%= form_with(model: @product, url: products_path, method: :post, local: true) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit 'Create Product' %>
  </div>
<% end %>

<%= link_to 'Back to Products', products_path %>

app/views/products/show.html.erb
<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
    <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% else %>

  <p>Image attached: <%= @product.image.attached? ? 'Yes' : 'No' %></p>

  <p>
    Image:
    <% if @product.image.attached? %>
      <%= image_tag @product.image, class: 'product-image'%>
    <% else %>
      No image attached.
    <% end %>
  </p>
  <%  byebug%>
    <%= link_to "Place Order", order_path %><br>


  <!-- link_to "Place Order", vendor_path(@product.vendor)  -->
  <%= link_to "Back to products", products_path %>
<% end %>